---
functional:
  - Пользователь должен иметь возможность создать игру, выбрав уровень сложности
  - Пользователь должен иметь возможность выбрать оппонента для игры (другого пользователя, друга или бота)
  - Пользователь должен иметь возможность установить лимит времени для игры
  - Пользователь должен иметь возможность выбрать задание для игры из списка
  - Пользователь должен иметь возможность создать игру с заданием, выбранным в случайном порядке
  - Пользователь должен иметь возможность отфильтровать задания по тегам
  - Пользователь должен иметь возможность зарегистрироваться с использованием email, социальных сетей и т.д.
  - Пользователь должен иметь возможность авторизоваться 
  - Пользователь должен иметь возможность восстановить пароль
  - Пользователь должен иметь возможность сыграть в игру без регистрации
  - Пользователь должен иметь возможность просматривать информацию о себе и других пользователях (никнейм, ранг, статистика, список решенных задач, активность на сайте)
  - Наличие встроенного редактора кода с подсветкой синтаксиса
  - Наличие автодополнения кода
  - Наличие чата для общения между участниками во время игры
  - Пользователь должен иметь возможность общаться с другими пользователями в общем чате в лобби
  - Пользователь должен иметь возможность общаться в приватном чате с другим пользователем
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен быть интуитивно понятным
  - Сайт должен соответствовать общепринятым стандартам веб-разработки
  - Сайт должен иметь современный и привлекательный дизайн, который будет мотивировать пользователей к участию в играх и турнирах
  - Создание сообщества вокруг сайта, где пользователи могут общаться, делиться опытом и задавать вопросы
  - Сайт должен мотивировать пользователей к участию в играх и улучшению своих навыков программирования (награды)
